import {
  ArrowLeft,
  ArrowRight,
  ArrowRightLeft,
  Award,
  BarChart3,
  BookOpen,
  BriefcaseBusiness,
  Building2,
  Calendar,
  Check,
  ChartColumn,
  CircleCheck,
  CircleDashed,
  CircleDot,
  CircleX,
  ClipboardPaste,
  Code,
  Compass,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleQuestionMark,
  Clock,
  Copy,
  Database,
  ExternalLink,
  Eye,
  EyeOff,
  FileCheck,
  FileText,
  Flame,
  Folder,
  GraduationCap,
  Handshake,
  House,
  Hourglass,
  Layers,
  LayoutDashboard,
  Lightbulb,
  ListChecks,
  ListTree,
  Lock,
  LogOut,
  Mail,
  Map,
  MapPin,
  Medal,
  Megaphone,
  Menu,
  MessageCircleQuestionMark,
  Milestone,
  Palette,
  Phone,
  Play,
  Plus,
  RotateCcw,
  Route,
  Send,
  ShieldCheck,
  SkipForward,
  Sparkles,
  SquarePlay,
  Settings,
  Target,
  Timer,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Video,
  User,
  Users,
  Wallet,
  X,
  type LucideIcon,
  type LucideProps,
} from "lucide-react"

/**
 * O único ponto do app que traduz "nome de ícone" em componente.
 *
 * O `site.ts` guarda apenas a string (`icone: "users"`). Assim a copy não
 * precisa importar nada e trocar o ícone de um item de menu é editar uma
 * palavra. Ícone novo? Importe do lucide e acrescente uma linha aqui.
 */
const ICONES = {
  "layout-dashboard": LayoutDashboard,
  users: Users,
  calendar: Calendar,
  settings: Settings,
  menu: Menu,
  fechar: X,
  sair: LogOut,
  mais: Plus,
  anterior: ChevronLeft,
  proximo: ChevronRight,
  ajuda: CircleQuestionMark,
  relogio: Clock,
  local: MapPin,
  usuario: User,
  email: Mail,
  telefone: Phone,
  empresa: Building2,
  remover: Trash2,
  check: Check,
  "seta-direita": ArrowRight,
  "seta-esquerda": ArrowLeft,
  mover: ArrowRightLeft,
  "link-externo": ExternalLink,
  copiar: Copy,
  alerta: TriangleAlert,
  paleta: Palette,
  dados: Database,
  restaurar: RotateCcw,
  dinheiro: Wallet,

  // O vocabulário deste app: a jornada de carreira, do diagnóstico à prática.
  inicio: House,
  carreiras: Compass,
  mapa: Route,
  aprender: SquarePlay,
  praticar: Target,
  progresso: TrendingUp,
  ranking: Trophy,
  perfil: User,
  desafio: Milestone,

  // as áreas profissionais
  aperto: Handshake,
  megafone: Megaphone,
  codigo: Code,
  pasta: Folder,
  estudar: BookOpen,
  paletaArea: Palette,

  // estados, medidas e peças da jornada
  nivel: BarChart3,
  grafico: ChartColumn,
  sequencia: Flame,
  tempo: Timer,
  conquista: Award,
  medalha: Medal,
  disponivel: CircleDot,
  pendente: CircleDashed,
  aguardando: Hourglass,
  bloqueado: Lock,
  lista: ListTree,
  video: Video,
  evidencia: FileCheck,
  enviar: Send,
  mapa2: Map,
  pular: SkipForward,
  virar: Eye,
  esconder: EyeOff,
  acertei: CircleCheck,
  errei: CircleX,
  formacao: GraduationCap,
  ideia: Lightbulb,
  comecar: Play,
  seguranca: ShieldCheck,
  gerar: Sparkles,
  conteudo: FileText,
  pergunta: MessageCircleQuestionMark,
  colar: ClipboardPaste,
} satisfies Record<string, LucideIcon>

export type NomeIcone = keyof typeof ICONES

type PropsIcone = LucideProps & {
  /** Chave do mapa acima. Nome desconhecido cai num círculo neutro em vez de sumir. */
  nome: string
}

export function Icone({ nome, strokeWidth = 1.75, ...resto }: PropsIcone) {
  const Glifo: LucideIcon = ICONES[nome as NomeIcone] ?? Circle

  // Decorativo por padrão: todo lugar que usa ícone aqui já tem rótulo em texto
  // ou `aria-label` no botão. Passe `aria-hidden={false}` se precisar do contrário.
  return <Glifo aria-hidden="true" strokeWidth={strokeWidth} {...resto} />
}
