import type { ItemFeed, PerfilProfissional, Trabalho } from "./types"

export const profissionais: PerfilProfissional[] = [
  {
    id: "prof-joao",
    nome: "João Ferreira",
    profissao: "Pedreiro",
    cidade: "Goiânia",
    bairro: "Setor Bueno",
    distanciaKm: 1.8,
    avaliacao: 4.9,
    trabalhosConcluidos: 47,
    disponivelAgora: true,
    valor: 250,
    formaCobranca: "diaria",
    raioKm: 15,
  },
  {
    id: "prof-ana",
    nome: "Ana Paula",
    profissao: "Diarista",
    cidade: "Goiânia",
    bairro: "Setor Marista",
    distanciaKm: 2.7,
    avaliacao: 4.8,
    trabalhosConcluidos: 89,
    disponivelAgora: true,
    valor: 180,
    formaCobranca: "diaria",
    raioKm: 12,
  },
  {
    id: "prof-carlos",
    nome: "Carlos Mendes",
    profissao: "Eletricista",
    cidade: "Goiânia",
    bairro: "Jardim Goiás",
    distanciaKm: 4.1,
    avaliacao: 4.7,
    trabalhosConcluidos: 63,
    disponivelAgora: false,
    valor: 120,
    formaCobranca: "servico",
    raioKm: 20,
  },
]

export const trabalhos: Trabalho[] = [
  {
    id: "job-reboco",
    titulo: "Reboco de muro residencial",
    categoria: "Pedreiro",
    cidade: "Goiânia",
    bairro: "Setor Marista",
    distanciaKm: 3.2,
    quando: "Amanhã",
    urgente: false,
    orcamentoMin: 250,
    orcamentoMax: 320,
    propostas: 4,
  },
  {
    id: "job-vazamento",
    titulo: "Conserto de vazamento",
    categoria: "Encanador",
    cidade: "Goiânia",
    bairro: "Setor Bueno",
    distanciaKm: 2.3,
    quando: "Agora",
    urgente: true,
    orcamentoMin: 180,
    orcamentoMax: 300,
    propostas: 2,
  },
  {
    id: "job-pintura",
    titulo: "Pintura de apartamento",
    categoria: "Pintor",
    cidade: "Goiânia",
    bairro: "Jardim América",
    distanciaKm: 5.4,
    quando: "Esta semana",
    urgente: false,
    orcamentoMin: 700,
    orcamentoMax: 1100,
    propostas: 6,
  },
]

export const feedInicial: ItemFeed[] = [
  { tipo: "disponibilidade", profissional: profissionais[0] },
  { tipo: "trabalho", trabalho: trabalhos[1] },
  { tipo: "disponibilidade", profissional: profissionais[1] },
  { tipo: "trabalho", trabalho: trabalhos[0] },
  { tipo: "disponibilidade", profissional: profissionais[2] },
  { tipo: "trabalho", trabalho: trabalhos[2] },
]
